---

- name: python apt
  become: yes
  apt: name={{item}} update_cache=yes state=present
  with_items:
    - software-properties-common
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-dev
    - python3-pip
    - graphviz-dev
    - python3-pygraphviz
    - python3-enchant

- name: python3 alias
  lineinfile:
    create: yes
    path: '~/.bash_aliases'
    line: 'alias python=python3'

- name: pip3 alias
  lineinfile:
    create: yes
    path: '~/.bash_aliases'
    line: 'alias pip=pip3'

- name: upgrade pip
  become: yes
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

- name: pip
  become: yes
  pip: name={{item}} executable=pip3
  with_items:
    - beautifulsoup4
    - gensim
    - hyperopt
    - ipython
    - jupyter
    - lxml
    - matplotlib
    - maxminddb-geolite2
    - nltk
    - numpy
    - pandas
    - Pillow
    - pydotplus
    - pyenchant
    - pymorphy2
    - pymorphy2-dicts-ru
    - pymorphy2-dicts-uk
    - pyodbc
    - python-geoip
    - python-geoip-geolite2
    - scipy
    - sklearn
    - unidecode
    - urllib3
    - xgboost
